/**
 * Reason the model stopped generating tokens, as reported by the Gemini API in
 * `response_metadata.finishReason` / `additional_kwargs.finishReason`.
 *
 * Implemented as a const-object + extracted type (rather than an enum) to allow both
 * value-level use (`FinishReason.SAFETY`) and type-level exhaustiveness checks.
 *
 * Keys are identical to their values so the set of valid values can be derived directly
 * from the object for parsing.
 *
 * `STOP` is the only successful outcome. Every other value means generation ended
 * abnormally and the response is degraded (truncated, filtered, or malformed).
 */
export const FinishReason = {
    /** Default API value. Documented as unused, treated as a generic failure if seen. */
    FINISH_REASON_UNSPECIFIED: "FINISH_REASON_UNSPECIFIED",
    /** Natural stop point of the model or a provided stop sequence. The only success case. */
    STOP: "STOP",
    /** The maximum number of tokens specified in the request was reached. */
    MAX_TOKENS: "MAX_TOKENS",
    /** The response candidate content was flagged for safety reasons. */
    SAFETY: "SAFETY",
    /** The response candidate content was flagged for recitation reasons. */
    RECITATION: "RECITATION",
    /** The response candidate content was flagged for using an unsupported language. */
    LANGUAGE: "LANGUAGE",
    /** Unknown reason. */
    OTHER: "OTHER",
    /** Generation stopped because the content contains forbidden terms. */
    BLOCKLIST: "BLOCKLIST",
    /** Generation stopped for potentially containing prohibited content. */
    PROHIBITED_CONTENT: "PROHIBITED_CONTENT",
    /** Generation stopped because the content potentially contains sensitive personal information. */
    SPII: "SPII",
    /** The function call generated by the model is invalid. */
    MALFORMED_FUNCTION_CALL: "MALFORMED_FUNCTION_CALL",
    /** Generation stopped because generated images contain safety violations. */
    IMAGE_SAFETY: "IMAGE_SAFETY",
    /** Image generation stopped because generated images have other prohibited content. */
    IMAGE_PROHIBITED_CONTENT: "IMAGE_PROHIBITED_CONTENT",
    /** Image generation stopped because of another miscellaneous issue. */
    IMAGE_OTHER: "IMAGE_OTHER",
    /** The model was expected to generate an image, but none was generated. */
    NO_IMAGE: "NO_IMAGE",
    /** Image generation stopped due to recitation. */
    IMAGE_RECITATION: "IMAGE_RECITATION",
    /** Model generated a tool call but no tools were enabled in the request. */
    UNEXPECTED_TOOL_CALL: "UNEXPECTED_TOOL_CALL",
    /** Model called too many tools consecutively, so the system exited execution. */
    TOO_MANY_TOOL_CALLS: "TOO_MANY_TOOL_CALLS",
    /** Request has at least one thought signature missing. */
    MISSING_THOUGHT_SIGNATURE: "MISSING_THOUGHT_SIGNATURE",
    /** Finished due to a malformed response. */
    MALFORMED_RESPONSE: "MALFORMED_RESPONSE",
    /** Request was filtered by an escalation rule. */
    ESCALATION: "ESCALATION",
} as const;

export type FinishReason = (typeof FinishReason)[keyof typeof FinishReason];

/** Lookup set for {@link parseFinishReason}, built once from the const object. */
const FINISH_REASON_VALUES: ReadonlySet<string> = new Set<string>(Object.values(FinishReason));

/**
 * Normalizes a raw `finishReason` value reported by the model provider.
 *
 * @param raw - The provider-reported value, typically a string but untyped at the boundary
 * @returns The matching {@link FinishReason}, or `null` when no reason was reported at all
 *   (an absent reason means the stream terminated prematurely, not that it succeeded).
 *   Unrecognized non-empty values map to {@link FinishReason.OTHER} so a newly added API
 *   enum member degrades into a generic failure instead of being read as success.
 */
export function parseFinishReason(raw: unknown): FinishReason | null {
    if (typeof raw !== "string" || raw.length === 0) return null;
    const normalized = raw.toUpperCase();
    // TYPE COERCION: guarded by the membership check against FINISH_REASON_VALUES, which is
    // built exclusively from FinishReason values, so the string is a FinishReason here.
    if (FINISH_REASON_VALUES.has(normalized)) return normalized as FinishReason;
    return FinishReason.OTHER;
}

/**
 * True when the model reported a reason other than a clean stop, meaning the response
 * is degraded and a retry is worthwhile. False for `STOP` and for an absent reason.
 */
export function isDegradedFinishReason(reason: FinishReason | null): boolean {
    return reason !== null && reason !== FinishReason.STOP;
}
