name: genieaiv2-test
services:
    db:
        image: postgres:18.3-alpine
        environment:
            POSTGRES_USER: genie_test
            POSTGRES_PASSWORD: genie_test
            POSTGRES_DB: genie_test
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5433:5432"
        volumes:
            - ./db_test:/var/lib/postgresql/data
        restart: unless-stopped
