name: genieaiv2-dev

services:
    db:
        image: postgres:18.3-alpine
        environment:
            POSTGRES_USER: genie
            POSTGRES_PASSWORD: genie
            POSTGRES_DB: genie
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
        restart: unless-stopped
