/**
 * Domain entity types for Discord message persistence.
 * Content is stored as an array of serialized LangChain message objects (via BaseMessage.toJSON())
 * to preserve all metadata including thoughtSignatures, tool calls, and response_metadata.
 */

export type MessageRole = "human" | "assistant";

/**
 * Identifies which Discord interaction pathway created a bot response row.
 * Used by the retry handler to reconstruct the correct intent and reply options
 * without re-parsing the original message content.
 *
 * - `"message_create"` — triggered by a regular chat message (@mention or command prefix)
 * - `"summary_command"` — triggered by the Summarize context menu command
 */
export type MessageInteractionType = "message_create" | "summary_command";

/**
 * A persisted Discord message within a reply chain.
 *
 * Only the message's own content is stored (not the full conversation),
 * allowing the recursive CTE to reconstruct the chain on demand.
 *
 * Each record can hold multiple serialized LangChain messages — e.g. for a bot
 * turn that involved tool use, this array would contain:
 * [triageAIMessage, ToolMessage, finalAIMessage].
 */
export interface DiscordMessage {
    /** UUID primary key */
    id: string;
    /** Discord's snowflake ID for this message */
    discordMessageId: string;
    /** Discord snowflake of the message this replies to, or null if chain root */
    repliesToDiscordId: string | null;
    channelId: string;
    /** Discord guild snowflake, or "@me" for DMs */
    guildId: string;
    role: MessageRole;
    /**
     * Discord user snowflake of the message author.
     * Set on all messages — bot messages carry the bot's own Discord user ID.
     */
    discordAuthorId: string;
    /**
     * Serialized LangChain BaseMessage objects (output of BaseMessage.toJSON()).
     * Deserialized by passing through JSON.parse (Bun SQL driver may return pre-parsed objects).
     */
    langchainMessages: Record<string, unknown>[];
    /**
     * Remaining retry attempts for this bot response.
     * Only set on retryable bot responses (fallback model was used).
     * NULL on human messages and non-retryable bot responses.
     */
    retriesLeft: number | null;
    /**
     * Whether this response was generated by a fallback model.
     * NULL on human messages and rows where this is not applicable.
     * Used to gate who may click the Retry button on a successful fallback response —
     * only the original prompter may retry when the response used a fallback.
     */
    usedFallback: boolean | null;
    /**
     * The interaction pathway that produced this bot response.
     * NULL on human messages and legacy rows predating this column.
     * Read by the retry handler to reconstruct intent and reply options (e.g. pingUser, replyPrefix).
     */
    interactionType: MessageInteractionType | null;
    /**
     * Discord snowflake of the user who invoked the interaction, when different from the
     * message author (e.g. a context menu command invoked on someone else's message).
     * NULL on human messages, message_create rows, and legacy rows.
     */
    interactionAuthorDiscordId: string | null;
    createdAt: Date;
}
