import { json, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import type { DiscordMessage } from "../../domain/message/Message.ts";

/**
 * Drizzle ORM schema for the messages table.
 *
 * Each row represents one Discord message in a reply chain.
 * Only the message's own content is stored — the full conversation context is
 * reconstructed on read via a recursive CTE traversing repliesToDiscordId.
 *
 * langchain_messages stores an array of serialized LangChain BaseMessage objects
 * (output of BaseMessage.toJSON()). One row can hold multiple LangChain messages
 * — e.g. a bot turn with tool use stores [triageAIMsg, ToolMsg, finalAIMsg].
 *
 * JSON (not JSONB) is used since we never perform key-level operations on this column.
 */
export const messages = pgTable("messages", {
    id: uuid("id").primaryKey().defaultRandom(),
    /** The Discord snowflake ID for this message */
    discordMessageId: text("discord_message_id").notNull().unique(),
    /** Discord snowflake of the parent message in the reply chain, null for chain root */
    repliesToDiscordId: text("replies_to_discord_id"),
    channelId: text("channel_id").notNull(),
    guildId: text("guild_id"),
    role: text("role", { enum: ["human", "assistant"] }).notNull(),
    /** Serialized LangChain BaseMessage objects stored as JSON array */
    langchainMessages: json("langchain_messages")
        .notNull()
        .$type<DiscordMessage["langchainMessages"]>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
});

/**
 * Tracks files uploaded to the Gemini Files API for use in LLM message content blocks.
 *
 * Each row corresponds to one Discord attachment that has been uploaded to Gemini.
 * Gemini files expire after 48 hours, so they are periodically re-uploaded. To avoid
 * mutating the persisted langchain_messages column, we use `original_gemini_url`
 * (the URI from the very first upload) as an immutable lookup key — it matches the
 * `url:` field stored in the HumanMessage content block. On refresh, only this row
 * is updated; the DB message record is never touched.
 *
 * gemini_file_name is `"files/<uuid>"` where the UUID is generated by us before each
 * upload. This makes the UNIQUE constraint safe (no collision with stale rows) and
 * keeps file names predictable for logging and cleanup.
 */
export const geminiFileUploads = pgTable("gemini_file_uploads", {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * The Gemini URI returned at first upload. Immutable — stored in LangChain
     * content blocks and used as the stable lookup key. Never updated after insert.
     */
    originalGeminiUrl: text("original_gemini_url").notNull().unique(),
    /**
     * The Gemini file name for the current upload (e.g. "files/<uuid>").
     * Generated by us as "files/<uuid>". Updated on each refresh.
     * Used to call ai.files.delete() before re-uploading.
     */
    geminiFileName: text("gemini_file_name").notNull().unique(),
    /** Current Gemini download URI. Updated on each refresh. */
    geminiUrl: text("gemini_url").notNull(),
    /** When the current Gemini file was uploaded. Updated on each refresh. */
    uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
    /** Discord attachment snowflake — stable identifier for re-downloading. */
    discordAttachmentId: text("discord_attachment_id").notNull(),
    /** Original filename as uploaded in Discord. Used as displayName on re-upload. */
    discordFilename: text("discord_filename").notNull(),
    /**
     * Discord message that originally created this upload.
     * ON DELETE CASCADE: deleting a message row removes its file upload records.
     */
    messageDiscordId: text("message_discord_id")
        .notNull()
        .references(() => messages.discordMessageId, { onDelete: "cascade" }),
});
