name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun ci

      - name: Run unit tests
        run: bun test --env-file .env.test tests/unit
        env:
          # TODO: remove once TAVILY_API_KEY is no longer required at startup (should be optional)
          TAVILY_API_KEY: dummy
